SELECT t.tbl, t.pol FROM (VALUES
('profiles','Profiles: public read'),
('profiles','Profiles: own update'),
('profiles','Profiles: admin update all'),
('profiles','Profiles: insert on signup'),
('user_roles','Roles: read own or admin'),
('user_roles','Roles: admin insert'),
('user_roles','Roles: admin update'),
('user_roles','Roles: admin delete'),
('member_categories','Categories: public read'),
('member_categories','Categories: admin manage'),
('credit_types','Credit types: public read'),
('credit_types','Credit types: admin manage'),
('pack_types','Pack types: read active or admin'),
('pack_types','Pack types: admin manage'),
('pack_type_categories','Pack type categories: public read'),
('pack_type_categories','Pack type categories: admin manage'),
('pack_purchases','Purchases: own read'),
('pack_purchases','Purchases: admin read all'),
('pack_purchases','Purchases: coach read all'),
('pack_purchases','Purchases: own insert'),
('pack_purchases','Purchases: admin insert'),
('pack_purchases','Purchases: admin update'),
('coupons','Coupons: read active'),
('coupons','Coupons: admin manage'),
('class_types','Class types: public read'),
('class_types','Class types: admin manage'),
('scheduled_classes','Classes: public read'),
('scheduled_classes','Classes: admin manage'),
('scheduled_classes','Classes: coach update own'),
('bookings','Bookings: own read'),
('bookings','Bookings: admin read all'),
('bookings','Bookings: coach read all classes'),
('bookings','Bookings: own insert'),
('bookings','Bookings: admin insert'),
('bookings','Bookings: coach insert'),
('bookings','Bookings: own cancel'),
('bookings','Bookings: admin update'),
('bookings','Bookings: coach update'),
('waitlist','Waitlist: own read'),
('waitlist','Waitlist: admin read'),
('waitlist','Waitlist: own insert'),
('waitlist','Waitlist: admin insert'),
('waitlist','Waitlist: own update'),
('waitlist','Waitlist: admin update'),
('waitlist','Waitlist: own delete'),
('notifications','Notifications: own read'),
('notifications','Notifications: own update'),
('notifications','Notifications: system insert'),
('app_settings','Settings: public read'),
('app_settings','Settings: admin manage'),
('activity_log','Activity log: admin read'),
('activity_log','Activity log: coach read'),
('activity_log','Activity log: own read'),
('activity_log','Activity log: system insert'),
('registration_fees','Reg fees: own read'),
('registration_fees','Reg fees: admin read'),
('registration_fees','Reg fees: insert'),
('registration_fees','Reg fees: admin all'),
('invoice_requests','Invoice: own read'),
('invoice_requests','Invoice: own insert'),
('invoice_requests','Invoice: admin all'),
('performance_types','PerfTypes: read all'),
('performance_types','PerfTypes: coach/admin insert'),
('performance_types','PerfTypes: coach/admin update'),
('performance_types','PerfTypes: coach/admin delete'),
('performances','Perf: own read'),
('performances','Perf: insert'),
('performances','Perf: update'),
('performances','Perf: delete'),
('subscriptions','Subscriptions: own read'),
('subscriptions','Subscriptions: admin all'),
('subscription_discounts','Sub discounts: own read'),
('subscription_discounts','Sub discounts: admin all'),
('referrals','referrals_own_read'),
('referrals','referrals_admin_all'),
('referral_rewards','rewards_own_read'),
('referral_rewards','rewards_admin_all'),
('member_badges','badges_own_read'),
('member_badges','badges_insert')
) AS t(tbl, pol)
LEFT JOIN pg_policies p ON p.tablename = t.tbl AND p.policyname = t.pol
WHERE p.policyname IS NULL
ORDER BY t.tbl, t.pol;
